import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { ReactLenis } from "lenis/react";
import { Theme } from "@radix-ui/themes";
import { Navbar } from "@/components/shared/navbar";
import { Footer } from "@/components/shared/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <Navbar/>
          <ReactLenis
            root
            options={{
              duration: 4,
              lerp: 2,
              smoothWheel: true,
              touchMultiplier: 1.5,
              syncTouch: true,
            }}
          >
            {children}
            <Footer />
          </ReactLenis>
        </Theme>
      </body>
    </html>
  );
}
